# This file was generated by GoReleaser. DO NOT EDIT.
cask "connect-iq-sdk-manager-cli" do
  name "connect-iq-sdk-manager-cli"
  desc "CLI to download connectIQ resources"
  homepage "https://github.com/lindell/connect-iq-sdk-manager-cli"
  version "0.8.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "connect-iq-sdk-manager-cli"
  bash_completion "completions/connect-iq-sdk-manager.bash"
  zsh_completion "completions/connect-iq-sdk-manager.zsh"
  fish_completion "completions/connect-iq-sdk-manager.fish"

  on_macos do
    on_intel do
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v#{version}/connect-iq-sdk-manager-cli_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/lindell/connect-iq-sdk-manager-cli"
      sha256 "d355fb6f4b448a2e4b551864d8e900caf6d1f57d9116a72c2d7347b7fd315749"
    end
    on_arm do
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v#{version}/connect-iq-sdk-manager-cli_#{version}_Darwin_ARM64.tar.gz",
        verified: "github.com/lindell/connect-iq-sdk-manager-cli"
      sha256 "afc3903034ec081942f3480ec140859d0bb73158c1a6badd64b57f88f6bf936b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v#{version}/connect-iq-sdk-manager-cli_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/lindell/connect-iq-sdk-manager-cli"
      sha256 "5d57b8f9cfcd02d3b3f48e19d6daca0480e4c6f627926f15d8617ef8a6f57e0b"
    end
    on_arm do
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v#{version}/connect-iq-sdk-manager-cli_#{version}_Linux_ARM64.tar.gz",
        verified: "github.com/lindell/connect-iq-sdk-manager-cli"
      sha256 "51f57489f0bfb549809631881bbaf04b79c3bd856180ca58e26cb1ac4a8e2f0e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/connect-iq-sdk-manager"]
    end
  end

  # No zap stanza required
end
